import { formatCurrency } from './utils/currency.js';
import { generateUniversalInvoice } from './utils/invoice.js';
import { showToast } from './utils/notifications.js';
import {
  blinkRow,
  convertFromMm,
  convertToFeetCalc,
  convertToMm,
  formatSavedDate,
  highlightMoveRow,
  validateNumericInput,
} from './utils/helpers.js';
import { getStorageItem, removeStorageItem, setStorageItem } from './utils/storage.js';
import { downloadElementAsJPG } from './utils/canvas.js';
import {
  addStandToQuotePad,
  closeStandCompareModal,
  generateStandPriceListHTML,
  openStandPage,
  openStandCompareModal,
  renderStandGrid,
  selectStand,
  updateStandQty,
} from './calculators/stand.js';
import {
  addBusinessCardToPad,
  attachBusinessCardListeners,
  closeBusinessCardCompareModal,
  copyBusinessCardInvoiceText,
  generateBusinessCardPriceListHTML,
  getBusinessCardPriceTier,
  handleBcCustomQtyChange,
  kiraBusinessCard,
  openBusinessCardCompareModal,
  renderBusinessCardPage,
} from './calculators/businessCard.js';
import {
  calculateLargeFormat,
  calculatePrintingLogic,
  calculateSignboard,
  kiraHarga,
  toggleCustomBorder,
  updateFinishingOptions,
  updatePreview,
  drawPreview,
} from './calculators/printRuntime.js';
import {
  initLargeFormat,
  openLargeFormatPage,
  renderLargeFormatCalculator,
  calculateLargeFormat as calculateLargeFormatCompat,
} from './calculators/largeFormat.js';
import {
  initSignboard,
  openSignboardPage,
  renderSignboardCalculator,
  calculateSignboard as calculateSignboardCompat,
} from './calculators/signboard.js';
import {
  clearDesign,
  handleDesignUpload,
  initArtworkDragAndDrop,
  processArtworkFile,
  renderPDFToImage,
  resetArtworkFit,
  rotateDesignImg,
  toggleArtLock,
  toggleArtworkTools,
  updateDesignDims,
} from './calculators/artworkTools.js';
import {
  capturePrintingCalculatorState,
  changeUnits,
  clearASizeHighlight,
  handleDimensionInput,
  restorePrintingCalculatorState,
  setASize,
  showCalculator,
  switchDimensions,
  toggleRatioLock,
} from './calculators/printShell.js';
import {
  downloadLargeFormatSVG,
  downloadPreviewCanvas,
  handleFinalDownload,
  setCustomDPI,
  setDownloadDPI,
  setFileType,
  toggleDownloadOptions,
} from './calculators/printExport.js';
import { addMugToPad, kiraMug, renderMugPage } from './giftItems/mug.js';
import { addBadgeToPad, kiraBadge, renderBadgePage } from './giftItems/badge.js';
import { addKeychainToPad, kiraKeychain, renderKeychainPage } from './giftItems/keychain.js';
import { addDTFToPad, addUVDTFToPad, closeDTFCompareModal, kiraDTF, kiraUVDTF, openDTFCompareModal, renderDTFPage } from './calculators/dtf.js';
import {
  addSublimationToPad,
  attachSublimationListeners,
  closeSublimationCompareModal,
  copySublimationInvoiceText,
  generateSublimationPriceListHTML,
  generateSublimationVariationsHTML,
  getSublimationBasePrice,
  getSublimationOptionCost,
  getSublimationSizeCost,
  handleSublimationCustomQtyChange,
  kiraSublimation,
  normalizeSublimationAddons,
  openSublimationCompareModal,
  renderSublimationCalculator,
} from './calculators/sublimation.js';
import {
  initSublimationSettings,
  renderSublimationSettingsTable,
  saveSublimationSettings,
  addRemoveSublimationAddonOption,
  openAddSublimationAddonGroupModal,
  closeAddSublimationAddonGroupModal,
  confirmAddSublimationAddonGroup,
  addRemoveSublimationAddonType,
  moveSublimationAddonOptionUp,
  moveSublimationAddonOptionDown,
  moveSublimationBasePriceUp,
  moveSublimationBasePriceDown,
  removeSublimationBasePriceByIndex,
  moveSublimationSizeUp,
  moveSublimationSizeDown,
  removeSublimationSizeByIndex,
  addRemoveSublimationQuantity,
  addRemoveSublimationSize,
  toggleSubAddonRulesPanel,
  _subSetAddonRule,
  toggleSublimationEditMode,
} from './calculators/sublimationSettings.js';
import {
  addLanyardToPad,
  attachLanyardListeners,
  closeLanyardCompareModal,
  copyLanyardInvoiceText,
  generateLanyardAddonsHTML,
  generateLanyardPriceListHTML,
  getLanyardPriceTierIndex,
  handleLanyardCustomQtyChange,
  kiraLanyard,
  openLanyardCompareModal,
  renderLanyardCalculator,
} from './calculators/lanyard.js';
import {
  addIdCardToPad,
  attachIDCardListeners,
  closeIDCardCompareModal,
  copyIdCardInvoice,
  ensureIDCardDefaultAddons,
  generateIDCardPriceListHTML,
  getIDCUnitPrice,
  getSelectedIDCardAddonData,
  handleIdCardCustomQtyChange,
  kiraIdCard,
  openIDCardCompareModal,
  renderIDCardCalculator,
} from './calculators/idCard.js';
import {
  addAcrylicToPad,
  adjustAcrylicPrice,
  attachAcrylicListeners,
  calculateAcrylicPrice,
  checkAcrylicManualInput,
  checkAcrylicPresetActive,
  closeAcrylicCompareModal,
  convertAcrylicValue,
  drawAcrylicPreview,
  fillAcrylicDropdown,
  fillAllAcrylicDropdowns,
  formatAcrylicUnitLabel,
  generateAcrylicSvg,
  getAcrylicBaseLabel,
  getAcrylicCalculatorHTML,
  getAcrylicSettingsModalHTML,
  handleAcrylicUnitChange,
  handleAcrylicUserToggle,
  highlightAcrylicPreset,
  openAcrylicCompareModal,
  populateAcrylicPriceTable,
  renderAcrylicCalculator,
  renderAcrylicMarkupRules,
  renderAcrylicPriceListHTML,
  setAcrylicASize,
  updateAcrylicPriceList,
  updateCopyableAcrylicInvoice,
} from './calculators/acrylic.js';
import {
  initInvitationCardSettings,
  toggleInvitationCardEditMode,
  renderInvitationCardSettingsTable,
  saveInvitationCardSettings,
  addInvitationCardQty,
  addInvitationCardSize,
  addInvitationCardMaterialInline,
  moveInvitationCardMaterialUp,
  moveInvitationCardMaterialDown,
  removeInvitationCardMaterialByIndex,
  removeInvitationCardQty,
  moveInvitationCardQtyUp,
  moveInvitationCardQtyDown,
  removeInvitationCardQtyByIndex,
  removeInvitationCardSize,
  openAddAddonGroupModal,
  closeAddAddonGroupModal,
  confirmAddAddonGroup,
  openManageSizesModal,
  closeManageSizesModal,
  redoManageSizes,
  addSizeRowToManageSizes,
  moveSizeRowUp,
  moveSizeRowDown,
  removeSizeRow,
  saveManageSizes,
  addInvitationCardAddonOptionInline,
  moveAddonOptionUp,
  moveAddonOptionDown,
  removeInvitationCardAddonType,
  removeInvitationCardAddonOption,
} from './calculators/invitationCardSettings.js';
import {
  initBusinessCardSettings,
  renderBusinessCardSettingsTable,
  openAddBusinessCardAddonGroupModal,
  closeAddBusinessCardAddonGroupModal,
  confirmAddBusinessCardAddonGroup,
  addBusinessCardAddonOptionInline,
  moveBusinessCardAddonOptionUp,
  moveBusinessCardAddonOptionDown,
  toggleBusinessCardEditMode,
  cancelBusinessCardEdit,
  saveBusinessCardSettings,
  addBusinessCardQty,
  closeAddQtyModal,
  confirmAddBusinessCardQty,
  removeBusinessCardQty,
  addBusinessCardMaterial,
  removeBusinessCardMaterialByIndex,
  moveBusinessCardMaterialUp,
  moveBusinessCardMaterialDown,
  addBusinessCardMaterialInline,
  removeBusinessCardMaterial,
  addBusinessCardAddonType,
  removeBusinessCardAddonType,
  addBusinessCardAddonOption,
  removeBusinessCardAddonOption,
} from './calculators/businessCardSettings.js';
import {
  initLanyardSettings,
  openManageLanyardSizesModal,
  closeManageLanyardSizesModal,
  addRowToManageLanyardSizes,
  moveLanyardSizeRowUp,
  moveLanyardSizeRowDown,
  removeLanyardSizeRow,
  redoManageLanyardSizes,
  saveManageLanyardSizes,
  renderLanyardSettingsTable,
  toggleLanyardAddonRulesPanel,
  _lanyardSetAddonRule,
  toggleLanyardEditMode,
  saveLanyardSettings,
  addLanyardQuantity,
  removeLanyardQtyByIndex,
  moveLanyardQtyUp,
  moveLanyardQtyDown,
  addLanyardSize,
  removeLanyardSizeByIndex,
  addLanyardAddonType,
  openAddLanyardAddonGroupModal,
  closeAddLanyardAddonGroupModal,
  confirmAddLanyardAddonGroup,
  removeLanyardAddonType,
  addLanyardAddonOptionInline,
  removeLanyardAddonOption,
  moveLanyardAddonOptionUp,
  moveLanyardAddonOptionDown,
} from './calculators/lanyardSettings.js';
import {
  initStampSettings,
  generateRandomColor,
  openManageStampCategoriesModal,
  closeManageStampCategoriesModal,
  openColorPickerModal,
  closeColorPickerModal,
  confirmColorPicker,
  rgbToHex,
  addRowToManageStampCategories,
  moveStampCategoryRowUp,
  moveStampCategoryRowDown,
  removeStampCategoryRow,
  redoManageStampCategories,
  saveManageStampCategories,
  renderStampSettingsTable,
  toggleStampCategoryEdit,
  cancelStampCategoryEdit,
  addStampToCategory,
  saveStampCategory,
  moveStampUp,
  moveStampDown,
  deleteStamp,
} from './calculators/stampSettings.js';
import {
  initAcrylicSettings,
  syncAcrylicPriceInputsToState,
  syncAcrylicMarkupInputsToState,
  addAcrylicPriceRow,
  moveAcrylicPriceUp,
  moveAcrylicPriceDown,
  removeAcrylicPriceRow,
  addAcrylicMarkupRule,
  moveAcrylicMarkupRuleUp,
  moveAcrylicMarkupRuleDown,
  removeAcrylicMarkupRule,
  toggleAcrylicSettingsEditMode,
  cancelAcrylicSettingsEdit,
  saveAcrylicSettingsSection,
  renderAcrylicPricingSettingsTable,
} from './calculators/acrylicSettings.js';
import {
  initIdCardSettings,
  renderIDCardSettingsTable,
  toggleIDCardEditMode,
  saveIDCardSettings,
  moveIDCardQtyUp,
  moveIDCardQtyDown,
  removeIDCardQtyByIndex,
  addIDCardAddonType,
  addIDCardAddonOption,
  moveIDCardAddonOptionUp,
  moveIDCardAddonOptionDown,
  openAddIDCardAddonGroupModal,
  closeAddIDCardAddonGroupModal,
  confirmAddIDCardAddonGroup,
} from './calculators/idCardSettings.js';
import {
  addStampToPad,
  calculateStampPrice,
  changeStampQty,
  closeStampCompareModal,
  copyStampInvoice,
  openStampPage,
  openStampCompareModal,
  renderStampPage,
  renderStampPriceList,
  renderStampPreview,
  selectStamp,
  setStampInk,
} from './calculators/stamp.js';
import {
  init as initSticker,
  getPaperSizeValue,
  buildPaperSizePresetMap,
  getDefaultPaperSize,
  convertToInches,
  convertFromInches,
  updateArtworkDimensions,
  toggleArtworkUnit,
  toggleCustomPaperUnit,
  syncStickerDropdownLabel,
  syncStickerEditorDropdowns,
  closeAllStickerDropdowns,
  toggleGenericStickerDropdown,
  selectGenericStickerDropdownOption,
  toggleStickerArtworkUnitDropdown,
  selectStickerArtworkUnitOption,
  toggleSpacingUnit,
  updatePaperSizeOptions,
  activatePresetButton,
  applyPresetArtworkSize,
  handleImageUpload,
  clearUploadedImage,
  setStickerDownloadDPI,
  setStickerCustomDPI,
  setStickerFileType,
  setStickerDownloadMode,
  toggleStickerArtworkTools,
  toggleStickerDownloadOptions,
  toggleStickerSpacingPanel,
  toggleStickerSmartFinderPanel,
  handleStickerFinalDownload,
  updateStickerDesignFields,
  updateStickerDesignDims,
  rotateStickerDesignImg,
  toggleStickerArtLock,
  resetStickerArtworkFit,
  downloadStickerCanvas,
  downloadStickerArtwork,
  downloadStickerAllShapes,
  copyStickerInvoiceText,
  addStickerToPad,
  setActiveControlButton,
  togglePaperLockRatio,
  rotatePaper,
  toggleLockRatio,
  setFreeSize,
  revertToOriginalSize,
  resizeArtworkToFitPaper,
  rotateArtwork,
  handleLayoutModeChange,
  calculateLayout,
  renderStickerPriceTable,
  sfCalcQty,
  generateStickersArray,
  calculateActualFitCount,
  setSFShape,
  setSFMode,
  toggleSFUnit,
  sfBlinkInputs,
  toggleSFTable,
  applySFResult,
  drawCanvas,
  updatePaperSize,
  toggleStickerPaperDropdown,
  selectStickerPaperOption,
  toggleCustomPaperSize,
  getInputInInches,
  resetSpacing,
  changeInputValue,
  initStickerEditor,
  toggleStickerDropdown,
  selectStickerMaterialOption,
  getStickerEditorHTML,
  renderStickerLayoutEditor,
  runStickerSmartFinder,
  rerunLastStickerSmartFinder,
  selectStickerPaperUnitOption,
  toggleStickerPaperUnitDropdown,
  getStickerPanelStates,
} from './stickers/sticker.js';
import {
  buildPaperSizePresetMap as buildStickerDataPaperSizePresetMap,
  getDefaultPaperSize as getStickerDataDefaultPaperSize,
  getPaperSizeValue as getStickerDataPaperSizeValue,
} from './stickers/stickerData.js';
import {
  SUBLIMATION_MIGRATION_VERSION,
  needsSublimationMigration,
  migrateSublimationStickerState,
} from './stickers/sublimationMigration.js';
import {
  addInvitationCardToPad,
  attachInvitationListeners,
  closeInvitationCompareModal,
  copyInvitationCardInvoiceText,
  generateInvitationPriceListHTML,
  getInvitationPriceTier,
  handleInvCardCustomQtyChange,
  kiraInvitationCard,
  openInvitationCompareModal,
  renderInvitationCardCalculator,
} from './calculators/invitationCard.js';
import {
  init as initQuotePad,
  getQuotePadItems,
  getCurrentQuoteName,
  addItemToQuotePad,
  openOrCloseQuotePad,
  toggleQuotePad,
  toggleQuotePadView,
  addOpenItemToPad,
  updateOpenItemField,
  renderQuotePad,
  initQuotePadSortable,
  updateGrandTotalDisplay,
  adjustQuoteItemQuantity,
  updateQuoteItemPrice,
  updateQuoteItemQuantity,
  autoResizeTextarea,
  updateQuoteName,
  updateQuoteItemTitle,
  updateQuoteItemDetail,
  updateQuoteItemCombinedDetails,
  duplicateQuotePadItem,
  removeFromPad,
  clearPad,
  copyAllFromPad,
  getQuoteSummary,
  saveQuote,
  renderLoadQuotePage,
  loadSelectedQuote,
  deleteSavedQuote,
  filterSavedQuotes,
  showQuotePreview,
  closeQuotePreviewModal,
  renameSavedQuote,
  duplicateSavedQuote,
  exportQuotes,
  importQuotes,
} from './quotePad.js';

export function registerAppModules(target = window) {
  const existingModules = target.appModules || {};

  target.appModules = {
    ...existingModules,
    currency: {
      ...(existingModules.currency || {}),
      formatCurrency,
    },
    invoice: {
      ...(existingModules.invoice || {}),
      generateUniversalInvoice,
    },
    notifications: {
      ...(existingModules.notifications || {}),
      showToast,
    },
    helpers: {
      ...(existingModules.helpers || {}),
      blinkRow,
      convertFromMm,
      convertToFeetCalc,
      convertToMm,
      formatSavedDate,
      highlightMoveRow,
      validateNumericInput,
    },
    storage: {
      ...(existingModules.storage || {}),
      getStorageItem,
      removeStorageItem,
      setStorageItem,
    },
    canvas: {
      ...(existingModules.canvas || {}),
      downloadElementAsJPG,
    },
    quotePad: {
      ...(existingModules.quotePad || {}),
      init: initQuotePad,
      getQuotePadItems,
      getCurrentQuoteName,
      addItemToQuotePad,
      openOrCloseQuotePad,
      toggleQuotePad,
      toggleQuotePadView,
      addOpenItemToPad,
      updateOpenItemField,
      renderQuotePad,
      initQuotePadSortable,
      updateGrandTotalDisplay,
      adjustQuoteItemQuantity,
      updateQuoteItemPrice,
      updateQuoteItemQuantity,
      autoResizeTextarea,
      updateQuoteName,
      updateQuoteItemTitle,
      updateQuoteItemDetail,
      updateQuoteItemCombinedDetails,
      duplicateQuotePadItem,
      removeFromPad,
      clearPad,
      copyAllFromPad,
      getQuoteSummary,
      saveQuote,
      renderLoadQuotePage,
      loadSelectedQuote,
      deleteSavedQuote,
      filterSavedQuotes,
      showQuotePreview,
      closeQuotePreviewModal,
      renameSavedQuote,
      duplicateSavedQuote,
      exportQuotes,
      importQuotes,
    },
    stand: {
      ...(existingModules.stand || {}),
      addStandToQuotePad,
      closeStandCompareModal,
      generateStandPriceListHTML,
      openStandPage,
      openStandCompareModal,
      renderStandGrid,
      selectStand,
      updateStandQty,
    },
    invitationCard: {
      ...(existingModules.invitationCard || {}),
      addInvitationCardToPad,
      attachInvitationListeners,
      closeInvitationCompareModal,
      copyInvitationCardInvoiceText,
      generateInvitationPriceListHTML,
      getInvitationPriceTier,
      handleInvCardCustomQtyChange,
      kiraInvitationCard,
      openInvitationCompareModal,
      renderInvitationCardCalculator,
    },
    businessCard: {
      ...(existingModules.businessCard || {}),
      addBusinessCardToPad,
      attachBusinessCardListeners,
      closeBusinessCardCompareModal,
      copyBusinessCardInvoiceText,
      generateBusinessCardPriceListHTML,
      getBusinessCardPriceTier,
      handleBcCustomQtyChange,
      kiraBusinessCard,
      openBusinessCardCompareModal,
      renderBusinessCardPage,
    },
    printRuntime: {
      ...(existingModules.printRuntime || {}),
      calculateLargeFormat,
      calculatePrintingLogic,
      calculateSignboard,
      drawPreview,
      kiraHarga,
      toggleCustomBorder,
      updateFinishingOptions,
      updatePreview,
    },
    largeFormat: {
      ...(existingModules.largeFormat || {}),
      initLargeFormat,
      openLargeFormatPage,
      renderLargeFormatCalculator,
      calculateLargeFormat: calculateLargeFormatCompat,
    },
    signboard: {
      ...(existingModules.signboard || {}),
      initSignboard,
      openSignboardPage,
      renderSignboardCalculator,
      calculateSignboard: calculateSignboardCompat,
    },
    printExport: {
      ...(existingModules.printExport || {}),
      downloadLargeFormatSVG,
      downloadPreviewCanvas,
      handleFinalDownload,
      setCustomDPI,
      setDownloadDPI,
      setFileType,
      toggleDownloadOptions,
    },
    artworkTools: {
      ...(existingModules.artworkTools || {}),
      clearDesign,
      handleDesignUpload,
      initArtworkDragAndDrop,
      processArtworkFile,
      renderPDFToImage,
      resetArtworkFit,
      rotateDesignImg,
      toggleArtLock,
      toggleArtworkTools,
      updateDesignDims,
    },
    printShell: {
      ...(existingModules.printShell || {}),
      capturePrintingCalculatorState,
      changeUnits,
      clearASizeHighlight,
      handleDimensionInput,
      restorePrintingCalculatorState,
      setASize,
      showCalculator,
      switchDimensions,
      toggleRatioLock,
    },
    mug: {
      ...(existingModules.mug || {}),
      addMugToPad,
      kiraMug,
      renderMugPage,
    },
    badge: {
      ...(existingModules.badge || {}),
      addBadgeToPad,
      kiraBadge,
      renderBadgePage,
    },
    keychain: {
      ...(existingModules.keychain || {}),
      addKeychainToPad,
      kiraKeychain,
      renderKeychainPage,
    },
    dtf: {
      ...(existingModules.dtf || {}),
      addDTFToPad,
      addUVDTFToPad,
      closeDTFCompareModal,
      kiraDTF,
      kiraUVDTF,
      openDTFCompareModal,
      renderDTFPage,
    },
    sublimation: {
      ...(existingModules.sublimation || {}),
      addSublimationToPad,
      attachSublimationListeners,
      closeSublimationCompareModal,
      copySublimationInvoiceText,
      generateSublimationPriceListHTML,
      generateSublimationVariationsHTML,
      getSublimationBasePrice,
      getSublimationOptionCost,
      getSublimationSizeCost,
      handleSublimationCustomQtyChange,
      kiraSublimation,
      normalizeSublimationAddons,
      openSublimationCompareModal,
      renderSublimationCalculator,
    },
    sublimationSettings: {
      ...(existingModules.sublimationSettings || {}),
      initSublimationSettings,
      renderSublimationSettingsTable,
      saveSublimationSettings,
      addRemoveSublimationAddonOption,
      openAddSublimationAddonGroupModal,
      closeAddSublimationAddonGroupModal,
      confirmAddSublimationAddonGroup,
      addRemoveSublimationAddonType,
      moveSublimationAddonOptionUp,
      moveSublimationAddonOptionDown,
      moveSublimationBasePriceUp,
      moveSublimationBasePriceDown,
      removeSublimationBasePriceByIndex,
      moveSublimationSizeUp,
      moveSublimationSizeDown,
      removeSublimationSizeByIndex,
      addRemoveSublimationQuantity,
      addRemoveSublimationSize,
      toggleSubAddonRulesPanel,
      _subSetAddonRule,
      toggleSublimationEditMode,
    },
    lanyard: {
      ...(existingModules.lanyard || {}),
      addLanyardToPad,
      attachLanyardListeners,
      closeLanyardCompareModal,
      copyLanyardInvoiceText,
      generateLanyardAddonsHTML,
      generateLanyardPriceListHTML,
      getLanyardPriceTierIndex,
      handleLanyardCustomQtyChange,
      kiraLanyard,
      openLanyardCompareModal,
      renderLanyardCalculator,
    },
    idCard: {
      ...(existingModules.idCard || {}),
      addIdCardToPad,
      attachIDCardListeners,
      closeIDCardCompareModal,
      copyIdCardInvoice,
      ensureIDCardDefaultAddons,
      generateIDCardPriceListHTML,
      getIDCUnitPrice,
      getSelectedIDCardAddonData,
      handleIdCardCustomQtyChange,
      kiraIdCard,
      openIDCardCompareModal,
      renderIDCardCalculator,
    },
    acrylic: {
      ...(existingModules.acrylic || {}),
      addAcrylicToPad,
      adjustAcrylicPrice,
      attachAcrylicListeners,
      calculateAcrylicPrice,
      checkAcrylicManualInput,
      checkAcrylicPresetActive,
      closeAcrylicCompareModal,
      convertAcrylicValue,
      drawAcrylicPreview,
      fillAcrylicDropdown,
      fillAllAcrylicDropdowns,
      formatAcrylicUnitLabel,
      generateAcrylicSvg,
      getAcrylicBaseLabel,
      getAcrylicCalculatorHTML,
      getAcrylicSettingsModalHTML,
      handleAcrylicUnitChange,
      handleAcrylicUserToggle,
      highlightAcrylicPreset,
      openAcrylicCompareModal,
      populateAcrylicPriceTable,
      renderAcrylicCalculator,
      renderAcrylicMarkupRules,
      renderAcrylicPriceListHTML,
      setAcrylicASize,
      updateAcrylicPriceList,
      updateCopyableAcrylicInvoice,
    },
    invitationCardSettings: {
      ...(existingModules.invitationCardSettings || {}),
      initInvitationCardSettings,
      toggleInvitationCardEditMode,
      renderInvitationCardSettingsTable,
      saveInvitationCardSettings,
      addInvitationCardQty,
      addInvitationCardSize,
      addInvitationCardMaterialInline,
      moveInvitationCardMaterialUp,
      moveInvitationCardMaterialDown,
      removeInvitationCardMaterialByIndex,
      removeInvitationCardQty,
      moveInvitationCardQtyUp,
      moveInvitationCardQtyDown,
      removeInvitationCardQtyByIndex,
      removeInvitationCardSize,
      openAddAddonGroupModal,
      closeAddAddonGroupModal,
      confirmAddAddonGroup,
      openManageSizesModal,
      closeManageSizesModal,
      redoManageSizes,
      addSizeRowToManageSizes,
      moveSizeRowUp,
      moveSizeRowDown,
      removeSizeRow,
      saveManageSizes,
      addInvitationCardAddonOptionInline,
      moveAddonOptionUp,
      moveAddonOptionDown,
      removeInvitationCardAddonType,
      removeInvitationCardAddonOption,
    },
    businessCardSettings: {
      ...(existingModules.businessCardSettings || {}),
      initBusinessCardSettings,
      renderBusinessCardSettingsTable,
      openAddBusinessCardAddonGroupModal,
      closeAddBusinessCardAddonGroupModal,
      confirmAddBusinessCardAddonGroup,
      addBusinessCardAddonOptionInline,
      moveBusinessCardAddonOptionUp,
      moveBusinessCardAddonOptionDown,
      toggleBusinessCardEditMode,
      cancelBusinessCardEdit,
      saveBusinessCardSettings,
      addBusinessCardQty,
      closeAddQtyModal,
      confirmAddBusinessCardQty,
      removeBusinessCardQty,
      addBusinessCardMaterial,
      removeBusinessCardMaterialByIndex,
      moveBusinessCardMaterialUp,
      moveBusinessCardMaterialDown,
      addBusinessCardMaterialInline,
      removeBusinessCardMaterial,
      addBusinessCardAddonType,
      removeBusinessCardAddonType,
      addBusinessCardAddonOption,
      removeBusinessCardAddonOption,
    },
    lanyardSettings: {
      ...(existingModules.lanyardSettings || {}),
      initLanyardSettings,
      openManageLanyardSizesModal,
      closeManageLanyardSizesModal,
      addRowToManageLanyardSizes,
      moveLanyardSizeRowUp,
      moveLanyardSizeRowDown,
      removeLanyardSizeRow,
      redoManageLanyardSizes,
      saveManageLanyardSizes,
      renderLanyardSettingsTable,
      toggleLanyardAddonRulesPanel,
      _lanyardSetAddonRule,
      toggleLanyardEditMode,
      saveLanyardSettings,
      addLanyardQuantity,
      removeLanyardQtyByIndex,
      moveLanyardQtyUp,
      moveLanyardQtyDown,
      addLanyardSize,
      removeLanyardSizeByIndex,
      addLanyardAddonType,
      openAddLanyardAddonGroupModal,
      closeAddLanyardAddonGroupModal,
      confirmAddLanyardAddonGroup,
      removeLanyardAddonType,
      addLanyardAddonOptionInline,
      removeLanyardAddonOption,
      moveLanyardAddonOptionUp,
      moveLanyardAddonOptionDown,
    },
    stampSettings: {
      ...(existingModules.stampSettings || {}),
      initStampSettings,
      generateRandomColor,
      openManageStampCategoriesModal,
      closeManageStampCategoriesModal,
      openColorPickerModal,
      closeColorPickerModal,
      confirmColorPicker,
      rgbToHex,
      addRowToManageStampCategories,
      moveStampCategoryRowUp,
      moveStampCategoryRowDown,
      removeStampCategoryRow,
      redoManageStampCategories,
      saveManageStampCategories,
      renderStampSettingsTable,
      toggleStampCategoryEdit,
      cancelStampCategoryEdit,
      addStampToCategory,
      saveStampCategory,
      moveStampUp,
      moveStampDown,
      deleteStamp,
    },
    acrylicSettings: {
      ...(existingModules.acrylicSettings || {}),
      initAcrylicSettings,
      syncAcrylicPriceInputsToState,
      syncAcrylicMarkupInputsToState,
      addAcrylicPriceRow,
      moveAcrylicPriceUp,
      moveAcrylicPriceDown,
      removeAcrylicPriceRow,
      addAcrylicMarkupRule,
      moveAcrylicMarkupRuleUp,
      moveAcrylicMarkupRuleDown,
      removeAcrylicMarkupRule,
      toggleAcrylicSettingsEditMode,
      cancelAcrylicSettingsEdit,
      saveAcrylicSettingsSection,
      renderAcrylicPricingSettingsTable,
    },
    idCardSettings: {
      ...(existingModules.idCardSettings || {}),
      initIdCardSettings,
      renderIDCardSettingsTable,
      toggleIDCardEditMode,
      saveIDCardSettings,
      moveIDCardQtyUp,
      moveIDCardQtyDown,
      removeIDCardQtyByIndex,
      addIDCardAddonType,
      addIDCardAddonOption,
      moveIDCardAddonOptionUp,
      moveIDCardAddonOptionDown,
      openAddIDCardAddonGroupModal,
      closeAddIDCardAddonGroupModal,
      confirmAddIDCardAddonGroup,
    },
    stamp: {
      ...(existingModules.stamp || {}),
      addStampToPad,
      calculateStampPrice,
      changeStampQty,
      closeStampCompareModal,
      copyStampInvoice,
      openStampPage,
      openStampCompareModal,
      renderStampPage,
      renderStampPriceList,
      renderStampPreview,
      selectStamp,
      setStampInk,
    },
    sticker: {
      ...(existingModules.sticker || {}),
      init: initSticker,
      getPaperSizeValue,
      buildPaperSizePresetMap,
      getDefaultPaperSize,
      convertToInches,
      convertFromInches,
      updateArtworkDimensions,
      toggleArtworkUnit,
      toggleCustomPaperUnit,
      syncStickerDropdownLabel,
      syncStickerEditorDropdowns,
      closeAllStickerDropdowns,
      toggleGenericStickerDropdown,
      selectGenericStickerDropdownOption,
      toggleStickerArtworkUnitDropdown,
      selectStickerArtworkUnitOption,
      toggleSpacingUnit,
      updatePaperSizeOptions,
      activatePresetButton,
      applyPresetArtworkSize,
      handleImageUpload,
      clearUploadedImage,
      setStickerDownloadDPI,
      setStickerCustomDPI,
      setStickerFileType,
      setStickerDownloadMode,
      toggleStickerArtworkTools,
      toggleStickerDownloadOptions,
      toggleStickerSpacingPanel,
      toggleStickerSmartFinderPanel,
      handleStickerFinalDownload,
      updateStickerDesignFields,
      updateStickerDesignDims,
      rotateStickerDesignImg,
      toggleStickerArtLock,
      resetStickerArtworkFit,
      downloadStickerCanvas,
      downloadStickerArtwork,
      downloadStickerAllShapes,
      copyStickerInvoiceText,
      addStickerToPad,
      setActiveControlButton,
      togglePaperLockRatio,
      rotatePaper,
      toggleLockRatio,
      setFreeSize,
      revertToOriginalSize,
      resizeArtworkToFitPaper,
      rotateArtwork,
      handleLayoutModeChange,
      calculateLayout,
      renderStickerPriceTable,
      sfCalcQty,
      generateStickersArray,
      calculateActualFitCount,
      setSFShape,
      setSFMode,
      toggleSFUnit,
      sfBlinkInputs,
      toggleSFTable,
      applySFResult,
      drawCanvas,
      updatePaperSize,
      toggleStickerPaperDropdown,
      selectStickerPaperOption,
      toggleCustomPaperSize,
      getInputInInches,
      resetSpacing,
      changeInputValue,
      initStickerEditor,
      toggleStickerDropdown,
      selectStickerMaterialOption,
      getStickerEditorHTML,
      renderStickerLayoutEditor,
      runStickerSmartFinder,
      rerunLastStickerSmartFinder,
      selectStickerPaperUnitOption,
      toggleStickerPaperUnitDropdown,
      getStickerPanelStates,
    },
    stickerData: {
      ...(existingModules.stickerData || {}),
      buildPaperSizePresetMap: buildStickerDataPaperSizePresetMap,
      getDefaultPaperSize: getStickerDataDefaultPaperSize,
      getPaperSizeValue: getStickerDataPaperSizeValue,
    },
    sublimationMigration: {
      ...(existingModules.sublimationMigration || {}),
      SUBLIMATION_MIGRATION_VERSION,
      needsSublimationMigration,
      migrateSublimationStickerState,
    },
  };

  return target.appModules;
}
